version: '3'

networks:
  fhirbase: {}

services:
  db:
    image: aidbox/aidboxdb:0.0.1-alpha3
    ports:
    - 54320:5432
    networks:
    - fhirbase
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       fhirbase

  fhirbase:
    build: ./embed/fhirbase.py/fhirbase-image
    networks:
    - fhirbase
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGHOST: db
      PGDATABASE: fhirbase

  cornsnake:
    build: ./cornsnake
    command: adev runserver __init__.py
    depends_on:
    - db
    networks:
    - fhirbase
    volumes:
    - ./cornsnake:/app/user
    - ./embed:/app/embed
    ports:
    - 8000:8000
    - 8001:8001
    environment:
      DEBUG: 'True'
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGHOST: db
      PGDATABASE: fhirbase
